version: '3.8'
services:
  music_app:
    image: music_app_image
    container_name: music_app_container
    build: .
    ports:
      - "${PORT}:${PORT}"
    env_file: .env
    environment:
      PORT: "${PORT}"
    depends_on:
      - music_db
    volumes:
      - ./:/usr/app/
      - /usr/app/node_modules
    networks:
      - music_bridge
    restart: always

  music_db:
    image: music_db_image
    container_name: music_db_container
    build: ./database/
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    env_file: .env
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    restart: always
    volumes:
      - music_db:/var/lib/music_db/data
    networks:
      - music_bridge

volumes:
  music_db:
    driver: local
    name: 'music_db'

networks:
  music_bridge:
    name: 'music_bridge'
    driver: bridge
