version: '3.8'
services:
  music_app:
    image: music_app_image
    container_name: music_app_container
    build: .
    environment:
      PORT: ${PORT}
      POSTGRES_HOST: music_db
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - music_db
    volumes:
      # - node_modules:/usr/app/node_modules
      - ./src:/usr/app/src
      - ./logs:/usr/app/logs
    networks:
      - music_bridge
    restart: always
    ports:
      - ${PORT}:${PORT}

  music_db:
    image: music_db_image
    container_name: music_db_container
    build: ./database/
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    restart: always
    volumes:
      - music_db_logs:/var/lib/postgresql/data
    networks:
      - music_bridge
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

volumes:
  music_db_logs:
  node_modules:

networks:
  music_bridge:
    driver: bridge
